print("=========================================")
print(" ")
print(" ")
print(" ")
print("This is an interpreter written in python for the upcoming programming language Verse. Feel free to test verse features to your hearts content")
print("Authors: Kariyampalli Christy, Turobin-Ort Marcel")
print("License: MIT")
print(" ")
print("=========================================")
print(" ")
print(" ██▒   █▓▓█████  ██▀███    ██████ ▓█████ ")
print("▓██░   █▒▓█   ▀ ▓██ ▒ ██▒▒██    ▒ ▓█   ▀ ")
print(" ▓██  █▒░▒███   ▓██ ░▄█ ▒░ ▓██▄   ▒███   ")
print("  ▒██ █░░▒▓█  ▄ ▒██▀▀█▄    ▒   ██▒▒▓█  ▄ ")
print("   ▒▀█░  ░▒████▒░██▓ ▒██▒▒██████▒▒░▒████▒")
print("   ░ ▐░  ░░ ▒░ ░░ ▒▓ ░▒▓░▒ ▒▓▒ ▒ ░░░ ▒░ ░")
print("   ░ ░░   ░ ░  ░  ░▒ ░ ▒░░ ░▒  ░ ░ ░ ░  ░")
print("     ░░     ░     ░░   ░ ░  ░  ░     ░   ")
print("      ░     ░  ░   ░           ░     ░  ░")
print("     ░                                   ")
print("                                         ")      